version: '3.4'

services:
  dockerapp:
    image: ${DOCKER_REGISTRY-}dockerapp
    build:
      context: .
      dockerfile: DockerApp/Dockerfile
    depends_on:
        - db
  db:
    image: postgres
    restart: always
    ports: 
        - 5532:5432
    environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=docker
    volumes:
        - ./db-data:/var/lib/postgresql/data
