version: '3.4'

services:
  dockerapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 8088:80
      - 8089:443
      - 5001:5001
      - 5000:5000